//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndexBuilder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9200")]
        public string BaseIndexUrl {
            get {
                return ((string)(this["BaseIndexUrl"]));
            }
            set {
                this["BaseIndexUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descriptions")]
        public string DescriptionIndexName {
            get {
                return ((string)(this["DescriptionIndexName"]));
            }
            set {
                this["DescriptionIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("relationships")]
        public string RelationshipIndexName {
            get {
                return ((string)(this["RelationshipIndexName"]));
            }
            set {
                this["RelationshipIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("clinicalfinding")]
        public string ClinicalFindingIndexName {
            get {
                return ((string)(this["ClinicalFindingIndexName"]));
            }
            set {
                this["ClinicalFindingIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("findingsite")]
        public string FindingSiteIndexName {
            get {
                return ((string)(this["FindingSiteIndexName"]));
            }
            set {
                this["FindingSiteIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("concept")]
        public string Entity {
            get {
                return ((string)(this["Entity"]));
            }
            set {
                this["Entity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\data\\descriptions.txt")]
        public string DescriptionsFilePath {
            get {
                return ((string)(this["DescriptionsFilePath"]));
            }
            set {
                this["DescriptionsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\data\\relationships.txt")]
        public string RelationshipsFilePath {
            get {
                return ((string)(this["RelationshipsFilePath"]));
            }
            set {
                this["RelationshipsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int DelimiterCode {
            get {
                return ((int)(this["DelimiterCode"]));
            }
            set {
                this["DelimiterCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("associatedmorphology")]
        public string AssociatedMorphologyIndexName {
            get {
                return ((string)(this["AssociatedMorphologyIndexName"]));
            }
            set {
                this["AssociatedMorphologyIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("associatedwith")]
        public string AssociatedWithIndexName {
            get {
                return ((string)(this["AssociatedWithIndexName"]));
            }
            set {
                this["AssociatedWithIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("causativeagent")]
        public string CausativeAgentIndexName {
            get {
                return ((string)(this["CausativeAgentIndexName"]));
            }
            set {
                this["CausativeAgentIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dueto")]
        public string DueToIndexName {
            get {
                return ((string)(this["DueToIndexName"]));
            }
            set {
                this["DueToIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("after")]
        public string AfterIndexName {
            get {
                return ((string)(this["AfterIndexName"]));
            }
            set {
                this["AfterIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("severity")]
        public string SeverityIndexName {
            get {
                return ((string)(this["SeverityIndexName"]));
            }
            set {
                this["SeverityIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("clinicalcourse")]
        public string ClinicalCourseIndexName {
            get {
                return ((string)(this["ClinicalCourseIndexName"]));
            }
            set {
                this["ClinicalCourseIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("episodicity")]
        public string EpisodicityIndexName {
            get {
                return ((string)(this["EpisodicityIndexName"]));
            }
            set {
                this["EpisodicityIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("interprets")]
        public string InterpretsIndexName {
            get {
                return ((string)(this["InterpretsIndexName"]));
            }
            set {
                this["InterpretsIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hasinterpretation")]
        public string HasInterpritationIndexName {
            get {
                return ((string)(this["HasInterpritationIndexName"]));
            }
            set {
                this["HasInterpritationIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pathologicalprocess")]
        public string PathologicalProcessIndexName {
            get {
                return ((string)(this["PathologicalProcessIndexName"]));
            }
            set {
                this["PathologicalProcessIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("occurence")]
        public string OccurenceIndexName {
            get {
                return ((string)(this["OccurenceIndexName"]));
            }
            set {
                this["OccurenceIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("findingmethod")]
        public string FindingMethodIndexName {
            get {
                return ((string)(this["FindingMethodIndexName"]));
            }
            set {
                this["FindingMethodIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("findinginformer")]
        public string FindingInformerIndexName {
            get {
                return ((string)(this["FindingInformerIndexName"]));
            }
            set {
                this["FindingInformerIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hasdefinitionalmanifestation")]
        public string HasDefinitionalManifestationIndexName {
            get {
                return ((string)(this["HasDefinitionalManifestationIndexName"]));
            }
            set {
                this["HasDefinitionalManifestationIndexName"] = value;
            }
        }
    }
}
